controller_list:
  - name: fake_manipulator_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - end_effector
initial:  # Define initial robot poses per group
  - group: manipulator
    pose: init